### ISSUE TITLE
Document Assert with Label Selector

### ISSUE THREAD

**Issue by kensipe** [kudobuilder/kuttl#121]
Test the following and work fine:

`00-install.yaml`
```
apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    environment: production
    app: nginx
spec:
  containers:
    - name: web
      image: nginx
```

`00-assert.yaml`
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    environment: production
status:
  phase: Running
```

Assert does NOT have name... working strictly off labels.
Needs to be documented
