### ISSUE TITLE
Enhance Shell Expansion with Defaults

### ISSUE THREAD

**Issue by kensipe** [kudobuilder/kuttl#130]
https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html

Would like to have a default value if ENV VAR not set as in:

```
${parameter:-word}
```

This should already work for `*.sh` shell scripts... but it would be great if the command expansion included it.

example:
```
apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  - command: kubectl kudo install kafka --namespace kafka-mwt -P ${KAFKA_PARAMETER_FILE:-params-kind}.yaml
    ignoredFailure: true
```
