### ISSUE TITLE
Embedded Commands Fail (unless in a script)

### ISSUE THREAD

**Issue by kensipe** [kudobuilder/kuttl#143]
Given:

```
apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    environment: production
    app: nginx
spec:
  containers:
    - name: web
      image: nginx
```

The command `kubectl get pod $(kubectl get pods --selector=app=nginx  -o=jsonpath="{.items[0].metadata.name}")  -o=jsonpath={.status.phase}` fails as a kuttl command, unless it is in a script file.

recommended using:  `kubectl get pod -l app=nginx -o=jsonpath={.items[].status.phase}`
