### ISSUE TITLE
Test harness should support asserting that a specific number of a resource exist when listing

### ISSUE THREAD

**Issue by justinbarrick** [kudobuilder/kuttl#158]
**What would you like to be added**:

In the test harness, you can match objects without specifying a name, for example:

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
status:
  state: READY
```

It should be possible to specify how many objects match.

**Why is this needed**:

This can be used to verify that a certain number of pods are ready or a certain number of plan executions exist.
