### ISSUE TITLE
TestStep delete of namespace fails

### ISSUE THREAD

**Issue by kensipe** [kudobuilder/kuttl#175]
```
apiVersion: kudo.dev/v1alpha1
kind: TestStep
delete:
- apiVersion: v1
  kind: Namespace
  name: spark
```

Fails with `   kuttl/harness/spark-job: case.go:196: object does not implement the Object interfaces`
