### ISSUE TITLE
kuttle assert can't handle testassert

### ISSUE THREAD

**Issue by hassenius** [kudobuilder/kuttl#221]
**Background**:
I have a `00-assert.yaml` looking like this:
```yaml
apiVersion: kudo.dev/v1alpha1
kind: TestAssert
timeout: 600
---
apiVersion: orchestrator.management.ibm.com/v1alpha1
kind: Installation
metadata:
  name: management-installation
  namespace: cp4m
status:
  phase: Running
```

`kubectl kuttl test <path>` yields the desired result of setting a custom timeout for the state to be reached for the specific assertion (at least it appears like it is, and the test case completes successfully without timing out after the default 30 seconds)

However, I would also like to use the same declared assets to "point" at an existing environment, so I would have expected to be able to just do `kubectl kuttl assert <path>/test-*/*-assert.yaml`

**What happened**:
`kubectl kuttl assert <path>/test-*/*-assert.yaml`
yields
```
object does not implement the Object interfaces
Error: asserts not valid
```

if I remove 
```yaml
apiVersion: kudo.dev/v1alpha1
kind: TestAssert
timeout: 600
---
```
from `*-assert.yaml` files I get the expected result:

```
assert is valid
```

or
```
resource Installation:cp4m/management-installation: .status.phase: value mismatch, expected: Foobar != actual: Running
Error: asserts not valid
```

**What you expected to happen**:
`kubectl kuttle assert` to be able to handle `kind: TestAssert` in the same way `kubectl kuttle test` does

**How to reproduce it (as minimally and precisely as possible)**:
Create a `00-assert.yaml` with a 
```yaml
apiVersion: kudo.dev/v1alpha1
kind: TestAssert
timeout: 600
---
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-14T11:09:22Z", GoVersion:"go1.14.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.3+47c0e71", GitCommit:"47c0e71", GitTreeState:"clean", BuildDate:"2020-09-17T23:10:07Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```
- KUTTL version (use `kubectl kuttl version`):
```
 $ kubectl kuttl version
KUTTL Version: version.Info{GitVersion:"0.6.1", GitCommit:"4908507", BuildDate:"2020-08-25T18:22:14Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): `Darwin`
- Kernel (e.g. `uname -a`): `19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64`
- Install tools: `brew`
- Others:
