### ISSUE TITLE
Asserts should be able to reference the namespace that kuttl has created

### ISSUE THREAD

**Issue by waciumawanjohi** [kudobuilder/kuttl#288]
**What would you like to be added**:
An ability to refer to the namespace in which tests are running.

I suspect this would look like some templating. e.g.:
```yaml
status:
  thingRef:
    namespace: $(NAMESPACE)
```
Alternatively, I could imagine this being implemented as a comment with special meaning to kuttl:

```yaml
status:
  thingRef:
    namespace: # //NAMESPACE//

```

**Why is this needed**:
I have resourceA and resourceB:
`00-setup.yaml`
```yaml
apiVersion: waciuma.com/v1alpha1
kind: thing
metadata:
  name: resource-a

---

apiVersion: waciuma.com/v1alpha1
kind: watcher
metadata:
  name: resource-b
```
I want to assert that resourceB's status contains an ObjectReference to resourceA. Currently, I can write the following:
`00-assert.yaml`
```yaml
apiVersion: waciuma.com/v1alpha1
kind: watcher
metadata:
  name: resource-b
status:
  thingRef:
    name: resource-a
```

I want to further assert that status.thingRef.namespace is correct.

I can not do this currently, unless I specify a namespace for the tests to run in.

I don't want to hardcode into the test suite what namespaces will be used in the tests. This will make tests brittle and more fragile moving from one environment to another. I cannot guarantee that another developer will have created a special namespace in the cluster that they are using for tests.

Related to #203
