### ISSUE TITLE
Asserts that a resource has been removed

### ISSUE THREAD

**Issue by rinormaloku** [kudobuilder/kuttl#301]
**Assert removal of resources**:
We have the TestStep of deleting a resource:
```
apiVersion: kuttl.dev/v1beta1
kind: TestStep
delete:
- apiVersion: v1
  kind: Deployment
  name: depl
```

But there is no way to Assert that for example, the replica sets are cleaned up.

**Why is this needed**:
This is needed to verify that after a resource is removed, controllers / operators are reconciling and setting the environment in the expected state when the resource is absent.
