### ISSUE TITLE
kuttl test flag --kind-containers

### ISSUE THREAD

**Issue by esatterwhite** [kudobuilder/kuttl#316]
**What would you like to be added**:
A command line flag for `kindContainers`

**Why is this needed**:
During a CI build process Docker tags are generated and have a random component and it isn't easily possible to include this in a static config file. It would be much easier to generate a command to execute.

**Comment by kensipe** [comment]
@esatterwhite could you provide more detail or acceptance criteria?   It isn't clear what the ask is here.  thanks for your involvement!

**Comment by esatterwhite** [comment]
Our build process generates a dynamic image tag and renders kubernetes manifests that are loaded into kuttl for testing. Not able to load that image directly in to kind using the static config because I don't really know what it is until it is running. 

So We're not able to assert that replicas are ready because they are all stuck in an image pull back off

```yaml
      state:                                                                                                                                                   
        waiting:                                                                                                                                               
          message: Back-off pulling image "us.gcr.io/logdna-k8s/kong:2.5.0-alpine.20210924T165522Z"                      
          reason: ImagePullBackOff  
```

if it were a command line flag, I could generate that command

```bash
kubectl kuttl test --config=kuttl.yaml --kind-containers=us.gcr.io/logdna-k8s/kong:2.5.0-alpine.20210924T165522Z
```

being able to specify the flag multiple times for multiple containers would be nice
