### ISSUE TITLE
Allow Kuttl to build a test matrix based on multiple test dimensions

### ISSUE THREAD

**Issue by soenkeliebau** [kudobuilder/kuttl#350]
**What would you like to be added**:

_Problem_
Currently Kuttl does not allow creating something like a test matrix which would allow testing any combination of a number of parameters.
For example testing an operator that rolls out a product would require copy and pasting test cases for every version that is under testing. This becomes even worse when the test is dependent on multiple dimensions, for example product version and java version.

Consider as an example the following dimensions:

Product Version:
- 0.1.0
- 0.2.0
- 0.2.1
- 0.3.0

Java Version:
- 8
- 11
- 16

This would require copy and pasting the same test case 12 times and adjusting the values manually in the test files, which is error prone, laborious and hard to maintain.

_Proposal_

We would like to be able to define test dimensions for Kuttl tests which can then be used to parameterize tests and effectively create a test matrix at runtime.

We have implemented external tooling around Kuttl at the moment to provide this functionality based on a test dimensions file that has the following structure:

````yaml
---
dimensions:
  - name: spark
    values:
      - 3.2.1
      - 3.3.0
  - name: hadoop
    values:
      - 3.2.0
      - 3.2.1
  - name: stackable
    values:
      - 0.4.0
tests:
  - name: spark-pi-private-s3
    dimensions:
      - spark
      - hadoop
      - stackable
  - name: spark-pi-public-s3
    dimensions:
      - spark
      - hadoop
      - stackable
````

This allows defining an arbitrary number of test dimensions along with values, as well as test cases that use these dimensions and which dimensions they actually use.
Our tooling then creates the needed list of test cases and runs a templating engine over the input kuttl files to generate the actual test files into those test case directories.

For the above example we'd generate the following list of test cases:

- spark-pi-private-s3
  - spark-3.2.1_hadoop-3.2.0_stackable-0.4.0
  - spark-3.3.0_hadoop-3.2.0_stackable-0.4.0
  - spark-3.2.1_hadoop-3.2.1_stackable-0.4.0
  - spark-3.3.0_hadoop-3.2.1_stackable-0.4.0
- spark-pi-public-s3
  - spark-3.2.1_hadoop-3.2.0_stackable-0.4.0
  - spark-3.3.0_hadoop-3.2.0_stackable-0.4.0
  - spark-3.2.1_hadoop-3.2.1_stackable-0.4.0
  - spark-3.3.0_hadoop-3.2.1_stackable-0.4.0
 
**Why is this needed**:
Kubernetes operators will quite often take lots of input dimensions into account for their behaviour, all of which should be tested.
The static nature of Kuttl at the moment makes it very hard to effectively test a large number of possible input combinations, even though its namespace isolation and parallelization would lend itself very well to quickly test large numbers of scenarios.

This suggestion, if implemented, would allow easily defining a larger test matrix to significantly enhance test coverage.

All of which I have written here is not a complete proposal yet, it is more an interest check, to see if it is worth starting the KEP process for this. If there is positive feedback for this I'll happily add more detail to this and transition it into a proper KEP.
