### ISSUE TITLE
Don't attempt to list pods in default namespace

### ISSUE THREAD

**Issue by erikgb** [kudobuilder/kuttl#368]
**What happened**:

When tracking down a bug in the recent kuttl 0.12.0 release, I notice that kuttl attempts to list pods in the default namespace when test fails. This is not the first time I observe this, but this time I used our simplest kuttl-setup, so this should be easy to reproduce.

````
--- FAIL: kuttl (20.67s)
    --- PASS: kuttl/harness (0.00s)
        --- PASS: kuttl/harness/default (4.21s)
FAIL
Error from server (Forbidden): pods is forbidden: User "system:serviceaccount:testing-operator-stas:stas-test-user" cannot list resource "pods" in API group "" in the namespace "default"
````

kuttl-config.yaml:
````yaml
apiVersion: kuttl.dev/v1beta1
kind: TestSuite
metadata:
  name: kuttl
namespace: systemcatalog-operator-test
reportFormat: xml
testDirs:
- tests/e2e
timeout: 120
````

**What you expected to happen**:

I am not sure why kuttl tries to list pods at all, but I would expect it to try listing pods **in the namespace where the actual tests are run**, and not the default namespace - where the test-user does not have access.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): multiple, probably not relevant
- KUTTL version (use `kubectl kuttl version`): 0.12.0 at that time, but bug is probably still present
- Cloud provider or hardware configuration: Openshift 4.9
- OS (e.g. from /etc/os-release): UBI (Red Hat), but probably not relevant
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
