### ISSUE TITLE
Background Process Readiness Probe

### ISSUE THREAD

**Issue by kensipe** [kudobuilder/kuttl#40]
When the BG process is started KUTTL moves forward with other commands (and tests).. however the commands could need the BG process to be ready to success.   We do want to the process in the background however we need to know when it is live.

An example use case:

```
commands:
  - command: ./bin/kubectl-kudo init --crd-only	  - command: ./bin/kubectl-kudo init --crd-only
  - command: ./bin/manager
    background: true
  - command: ./bin/kubectl-kudo install --skip-instance ./repository/cassandra/3.11/operator/	  
```

The `kudo install` command will fail if manager isn't ready.   We need manager to be "ready"  before the `install` command.
