### ISSUE TITLE
reportFormat in TestSuite

### ISSUE THREAD

**Issue by blezoray** [kudobuilder/kuttl#449]
Hello,

I have the following TestSuite file:
```yaml
apiVersion: kuttl.dev/v1beta1
kind: TestSuite
testDirs:
- ./tests/e2e
reportFormat: XML
namespace: mpms-tests-auto
```
The execution works fine but Kuttl continues to generate the report in JSON format.
Could you check that point ?

I use the version 0.14.0.

Rgds.
