### ISSUE TITLE
Assert if a field is missing from a resource

### ISSUE THREAD

**Issue by gibizer** [kudobuilder/kuttl#455]
**What would you like to be added**:

A way to assert if a field is missing from the resource.

**Why is this needed**:

For example as a test step I'm scaling down a Deployment to 0 replicas and I want to assert that 
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keystone
status:
  availableReplicas: 0
```
However when the `availableReplicas` is 0 the field itself is not returned from the api server so my assert fails.

**Comment by erikgb** [comment]
I think you can do this already, at least as a workaround, by using the ["errors" feature](https://kuttl.dev/docs/testing/asserts-errors.html#format). Continuing on your example, you could just add a `00-errors.yaml` (adjust the index to your test) file:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keystone
status:
  availableReplicas: {}
```
