### ISSUE TITLE
TestAssert is assumed to be a CRD in the cluster

### ISSUE THREAD

**Issue by iainsproat** [kudobuilder/kuttl#462]
**What happened**:

This is possibly a bug, or possibly my complete misunderstanding of how TestAssert is meant to work!

I have a `TestAssert` definition in `01-assert.yaml` file:

```yaml
apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 5
collectors:
  - type: command
    command: echo hello
```

kuttl reports the following:

```
case.go:366: retrieving API resource for kuttl.dev/v1beta1, Kind=TestAssert failed: the server could not find the requested resource
```

**What you expected to happen**:

TestAssert is recognised by kuttl and has the behaviour described in [the documentation](https://kuttl.dev/docs/testing/reference.html#testassert).

**How to reproduce it (as minimally and precisely as possible)**:

See above specification and below environment details.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.25.4
```

- KUTTL version (use `kubectl kuttl version`):

```
KUTTL Version: version.Info{GitVersion:"0.15.0", GitCommit:"f6d64c9", BuildDate:"2023-01-03T21:32:35Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"darwin/arm64"}
```

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by iblancasa** [comment]
This is not a bug. Maybe it should be explained in a better way in the documentation.

When you use a filename `xx-assert.yaml`, KUTTL expects to match exactly the object from your file. So, with this content file:
```yaml
apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 5
collectors:
  - type: command
    command: echo hello
```
KUTTL will try to look for a `TestAssert` object in your Kubernetes cluster.

Since what you want is KUTTL to "execute" that file, you need to rename your file from `01-assert.yaml` to something like  `01-check-command.yaml` for instance.
