### ISSUE TITLE
Wrong type for kindConfig

### ISSUE THREAD

**Issue by fhopfensperger** [kudobuilder/kuttl#476]
Hi kuttl team,

**What happened**:
`kindConfig` is of type [boolean](https://github.com/kudobuilder/kuttl/blame/f6d64c915c8dd9e2da354562c3d5c6fcf88aec2b/crds/testsuite_crd.yaml#L49)

**What you expected to happen**:
According to [code](https://github.com/kudobuilder/kuttl/blob/main/pkg/apis/testharness/v1beta1/test_types.go#L42) it should be `string`

**How to reproduce it (as minimally and precisely as possible)**:
If you use a JetBrains Enterprise IDE in combination with Kubernetes Plugin, you can import the CRD.
<img width="971" alt="image" src="https://github.com/kudobuilder/kuttl/assets/9072240/98e94d3a-1c56-445e-9720-ec528f68e8d7">
afterwards add a `.yaml` file to a project 
```yaml
apiVersion: kuttl.dev/v1beta1
kind: TestSuite
metadata:
  name: e2e
kindConfig: ./e2e/kind-config.yaml
```
you will see the syntax error immediately.
