### ISSUE TITLE
Suppress uninteresting parts of long object diffs

### ISSUE THREAD

**Issue by porridge** [kudobuilder/kuttl#497]
**What happened**:

Assert on something like a `Deployment`, for example:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: central
status:
  availableReplicas: 1
```

and the deployment's spec is non-trivial, you get this massive literally a few hundred lines long diff which mostly consists of `metadata.managedFields` (see #370) and contents of `spec` which is mostly irrelevant with the above assertion. This verbosity makes it somewhat hard to navigate the kuttl output, especially if you assert against several such deployments in single step.

**What you expected to happen**:

The pretty-diff output should omit long unnecessary fields.

**How to reproduce it (as minimally and precisely as possible)**:

See the test case in the PR which is coming up soon.
