### ISSUE TITLE
Add CEL expression support

### ISSUE THREAD

**Issue by kumar-mallikarjuna** [kudobuilder/kuttl#562]
**What would you like to be added**:
A Common Expression Language (CEL) based assertion semantic.

> The Common Expression Language (CEL) provides a standardized way to evaluate expressions, facilitating easier interoperability between different applications.

Reference: https://github.com/google/cel-spec

**Why is this needed**:

Currently, Kuttl lacks support for complex data manipulation in assertions. Here are a few examples where this limitation is apparent:
- Testing whether a Deployment has created _more than `n` Pods_.
  - While Kuttl supports equality testing, conditional matching poses a challenge.
- Slice assertion.
  - Kuttl's current method for handling slice comparison is somewhat obscure. Which becomes important especially when the order of elements in the slice is not fixed, which is common in Kubernetes (see https://github.com/kudobuilder/kuttl/issues/76#issuecomment-660944596).
  - Additionally, partially asserting slices is not possible (ref https://github.com/kudobuilder/kuttl/issues/76).

These issues could be resolved by incorporating a CEL engine into Kuttl, allowing for expression evaluation and more flexible assertions.

**How would this look like syntactically**:
```yaml
apiVersion: kuttl.dev/v1beta1
kind: TestAssert
celAssert:
  resources:
    - apiVersion: apps/v1
       kind: Deployment
       name: coredns
       namespace: kube-system
       id: resource
  expression: "resource.status.readyReplicas > 1"
```

---
Edit: Incorporate the comments from @porridge .
