### ISSUE TITLE
Assert at End of TestSuite Setup (Before Tests)

### ISSUE THREAD

**Issue by kensipe** [kudobuilder/kuttl#63]
A great strategy for "ensuring" a controller or resources is to have a step 0 assert of that instance running
see https://github.com/kudobuilder/kudo/pull/1473
test/e2e/cli-install-uninstall/00-assert.yaml
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kudo-manager
    control-plane: controller-manager
  namespace: kudo-system
status:
   phase: Running 
```

Assuming you may want this as a precondition on all tests... it would be great to assert this at the end of TestSuite setup prior to tests.

**Comment by kensipe** [comment]
something like:

```
apiVersion: kudo.dev/v1beta1
kind: TestSuite
crdDir: ./config/crds/
manifestDirs:
- ./test/manifests/
testDirs:
- ./test/integration
commands:
  - command: ./bin/manager
    background: true
startControlPlane: true
setup-assert:
    controller-running.yaml
```
