### ISSUE TITLE
Using variables in test steps

### ISSUE THREAD

**Issue by zmalik** [kudobuilder/kuttl#71]
**What would you like to be added**:
Support for using variables inside the KUTTL steps. Right now we can use env variables in command steps. But it would help if we could extend that to all test steps. Using env variables or other ways of providing variables. 

**Why is this needed**:
```
apiVersion: kudo.dev/v1beta1
kind: Instance
metadata:
  name: cassandra
spec:
  name: "cassandra"
  parameters:
    NODE_DOCKER_IMAGE: mesosphere/cassandra:<generated-value>
```
for example when updating a Kubernetes object as a step,  like in the above example, sometimes we need to add a runtime value to the test. In the above case the `<generated-value>`, which could come from env variables or from a file.
