### ISSUE TITLE
How to validate conditions

### ISSUE THREAD

**Issue by debianmaster** [kudobuilder/kuttl#75]
**What happened**:
I could not find docs to assert conditions on a object

**What you expected to happen**:
documentation for asserting status conditions 

**How to reproduce it (as minimally and precisely as possible)**:
i have an object with following conditions in status
```
status:
  conditions:
  - lastProbeTime: "2020-05-07T11:27:38Z"
    lastTransitionTime: "2020-05-07T11:27:43Z"
    status: "True"
    type: ProvisionRBAC
  - lastProbeTime: "2020-05-07T11:27:41Z"
    lastTransitionTime: "2020-05-07T11:27:43Z"
    status: "True"
    type: CheckAgent
  - lastProbeTime: "2020-05-07T11:27:43Z"
    lastTransitionTime: "2020-05-07T11:27:43Z"
    status: "True"
    type: SyncComponent
  health:
    phase: Healthy
    updated_at: "2020-05-07T11:28:45Z"
  lastUpdate: "2020-05-07T11:28:45Z"
  nodes: 1
  status: Success
```

How can i create an assertion what checks  if SyncComponent (array element) status is true

**Comment by kensipe** [comment]
thanks for creating the issue!
it is unclear what specifically you would want to assert on... 

1. you shouldn't assert on times (it would be interesting to consider if time expression is something we should assert on... meaning assert that it is a time format (without specific time info)
2.  we may need better support to assert in arrays... for instance `conditions:` contains and object.  may need an expressive language like rego.

it should be possible to assert:

```
# Expect the CRD to exist
apiVersion: <apiversion>
kind: <kind>
status:
  conditions:
  - type: ProvisionRBAC
    status: "True"
  - type: CheckAgent
    status: "True"
  - type: SyncComponent
    status: "True"
```
we have an example similar to this in our test suite: https://github.com/kudobuilder/kuttl/blob/master/pkg/test/test_data/crd-in-step/00-assert.yaml

we will need to take a look at this.
TODO:
1. look at assert array support
2. document this 

/cc: @debianmaster
