### ISSUE TITLE
Allow partial comparison of slices

### ISSUE THREAD

**Issue by alembiewski** [kudobuilder/kuttl#76]
**What would you like to be added**:

It would be great to check only the subset of a slice in a test step assertion. Currently, it is required to specify all the array elements, otherwise, a test fails with `slice length mismatch` error.

**Why is this needed**:

Here are some real-life pain points:
- if istio injection is enabled, a sidecar is running alongside with the main container in a pod, and it needs to be reflected in test assertions;
- testing mutating webhook, which updates environment variables or volume/volume mounts for some container in a pod, and a test case checks the applied patch;
- pod's status conditions (say, the goal of a test step to check the only one, final condition);
- and so on

**Comment by kensipe** [comment]
@alembiewski could you provide an example of what is required today and what you would like to see (yaml examples will help visualize).  This seems valuable.

**Comment by kensipe** [comment]
we need enough info to create a kep

**Comment by alembiewski** [comment]
Here is the example: let's say we have a custom resource `TrainingJob`, which describes some machine-learning training job, and it has a `status.conditions[]` field (slice). The job goes through several conditions before it reaches the final state. In my test case, I want to check the job is succeeded. Currently, to work-around the `slice length mismatch` error, my assert file looks like this:
```
kind: TrainingJob
metadata:
  name: ml-job
status:
  conditions:
  - reason: JobCreated      # I have to provide all the intermediate conditions here
  - reason: JobRunning      # to make kuttl happy
  - reason: JobSucceeded   <-- this is what I actually want to test
    status: "True"
    type: Succeeded
```
This is how I would like my assert to be:
```
kind: MLJob
metadata:
  name: ml-job
status:
  conditions:
  - reason: JobSucceeded
    status: "True"
    type: Succeeded
```
So the problem is that I have to specify all the conditions (but this could be env variables, volumes - any property with array type).

**Comment by kensipe** [comment]
This is related to #75 
Looking for better array support in asserts.   Looking for:
1. Disregard order to array
2. Partial array support (only assert what is expressed)

**Comment by porridge** [comment]
Please note that the workaround mentioned in https://github.com/kudobuilder/kuttl/issues/76#issuecomment-632112138 is fragile: we've seen cases where the elements appear in a different order, and this causes the test to fail.

**Comment by nic-hima** [comment]
Hey, looking at this from a slightly different lense (Gomega), it almost seems like you need something like: [ContainElement()](https://github.com/onsi/gomega/blob/46e0cd22c9d45e5745e994abc67b128504ad7727/matchers.go#L259-L270) .

> This is related to #75
> Looking for better array support in asserts. Looking for:
> 
>     1. Disregard order to array
> 
>     2. Partial array support (only assert what is expressed)

I have written quite a few tests imperatively (non-declarative) that boil down to something like https://github.com/kudobuilder/kuttl/issues/76#issuecomment-632112138 in code for operator testing. Could definitely see broader use-cases of this requested functionality!

**Comment by owais** [comment]
I'm writing an operator that injects a number of environment variables into pod container spec. The number of env vars it injects depends on a few factors which I might not want to necessarily test. Also some env vars have values that have some randomness them (e.g, a uuid). kuttl has no way to tell what the random value would be so it cannot test against the specific var. I'd like to leave out the random vars and test the rest with kuttl. This would give me enough confidence in an end-to-end test while I test fine grained logic in unit tests. Does this use case make sense?

**Comment by owais** [comment]
One more use case is where my operator injects the current namespace into the container spec as an environment variable. Right now my only workaround is to create a namespace with a well-known name and run the entire test inside that. This obviously adds other limitations. It would be nice if we could have some sort of variable substitution in asserts to test dynamic values like kuttl namespaces but still being able to test a slice partially would be even better as it solves many other such cases as well.

**Comment by owais** [comment]
Another case is `volumeMounts`. My operator mounts a specific volume on containers and I'd like to be able to test that with kuttl. However, k8s also appears to mount the following volume automatically:

```yaml
    volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
           name: kube-api-access-54d79
           readOnly: true
```

the volume name has a random component which cannot be predicted. I just want to be able to test that the operator injected a specific volume on a container. I don't care about what other volumes some other component may or may not be mounting. If the other volumes had predictable names, I could may be list them in my assertions even though they'd would make the tests look unclean and erode the intention of the assertions a bit but in this case I can't even do that as the name is randomly generated.

**Comment by cbandy** [comment]
The examples given above are all [lists of objects](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#lists-of-named-subobjects-preferred-over-maps) following Kubernetes conventions. When accepting a patch, the API server [treats these lists like maps](https://kubernetes.io/docs/reference/using-api/server-side-apply/#merge-strategy). Other examples can be found in the [API documentation](https://kubernetes.io/docs/reference/kubernetes-api/) with the note "Patch strategy: merge on key …" and the [OpenAPI specification](https://github.com/kubernetes/kubernetes/tree/master/api/openapi-spec) with `x-kubernetes-patch-merge-key`.

- Pod conditions match on their `type` field; [docs](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#PodStatus), [Go struct](https://releases.k8s.io/v1.24.0/staging/src/k8s.io/api/core/v1/types.go#L3813-L3814)
- Container volume mounts match on their `mountPath` field; [docs](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#volumes-1), [Go struct](https://releases.k8s.io/v1.24.0/staging/src/k8s.io/api/core/v1/types.go#L2363-L2364)

I'm not sure if or how KUTTL should incorporate this information.

Perhaps assertions need to be more expressive? Kubernetes is doing something with CEL to specify [cross-field validation](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#validation-rules) rules. Kyverno interprets [special characters](https://kyverno.io/docs/writing-policies/validate/#patterns) in YAML keys and values affect matching beyond simple equality. OPA has [Rego](https://www.openpolicyagent.org/docs/latest/policy-language/), etc.



Related: #152

**Comment by gberche-orange** [comment]
@shanproofpoint I'm using a TestAssert command as a workaround. 

```yaml
apiVersion: kuttl.dev/v1beta1
kind: TestAssert
commands:
- timeout: 40
  script: |
    kubectl wait --for=condition=Available deployment/spring-petclinic-medium --timeout 30s --namespace $NAMESPACE
---
# usual kuttl style assertion follows
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-medium
spec:
  template:
    spec:
      #! service binding operator injects a volume and volume mounts with the secret
      containers:
        - volumeMounts:
            - mountPath: /bindings/spring-petclinic-medium-postgresql
              name: spring-petclinic-medium-postgresql
[...]
````

This makes assertions harder to read. I'll try next to using the [bats detik](https://github.com/bats-core/bats-detik#using-regular-expressions) dsl for non-exact matches in TestAsserts as to be closer to "documentation by example" / bdd style asserts.
