### ISSUE TITLE
Object Selection with Selectors For Assert

### ISSUE THREAD

**Issue by kensipe** [kudobuilder/kuttl#94]
Currently a name must be provided for a resource to be asserted

We should allow for the selection thru labels

The use case is the creation of objects (like pods) with randomized names.   We need to be able to either:
1. retrieve the name and use the name or
2. select the object with another selector (labels)

**Comment by biancajiang** [comment]
The fact that kuttl assert can validate against an expected object's yaml is very valuable to us.  Given the yaml uses the same spec as the object itself can be powerful - native k8s objects' validation quickly w/o any learning curve of a different framework.

For objects with dynamic names -- all pods by deployments, dynamically provisioned PVs, the objects themselves already have labels.  When name is not specified, can the specified labels in assert be used as the default identifier -- selectors for the objects, without the test creators having to select them explicitly?

e.g. Assert a pod is successfully bound with a PV (omitting PVC assert) for its data volume with labels as the identifier (selector):
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/instance: app1
    app.kubernetes.io/name: myapp
spec:
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: myClaim
  containers:
    volumeMounts:
    - mountPath: /opt/data
      name: data
status:
  conditions:
  - status: "True"
    type: Ready
  phase: Running
```

PV assert:
```
apiVersion: v1
kind: PersistentVolume
spec:
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: myClaim
  volumeMode: Filesystem
status:
  phase: Bound
```

**Comment by kensipe** [comment]
testing shows this working... see #121

**Comment by kensipe** [comment]
checking labels with domain names works as well:

```
apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    environment: production
    app.kubernetes.io/name: myapp
spec:
  containers:
    - name: web
      image: nginx
```
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/name: myapp
status:
  phase: Running
```
I don't see an issue here... @biancajiang can you clarify an issue you are having?
